import assert from 'node:assert/strict';
import {angle,measure,summary,timing} from './dist/metrics.mjs';
const p=(x,y,visibility=1)=>({x,y,visibility});
assert.equal(angle(p(1,0),p(0,0),p(0,1)),90);
assert.equal(angle(p(-1,0),p(0,0),p(1,0)),180);
assert.equal(angle(p(1,0,.4),p(0,0),p(0,1)),null);
assert.equal(angle(p(0,0),p(0,0),p(0,1)),null);
const points=Array.from({length:33},()=>p(0,0,0));
points[12]=p(.5,.2);points[14]=p(.5,.4);points[16]=p(.7,.4);points[24]=p(.5,.6);points[26]=p(.5,.8);points[28]=p(.5,1);
const m=measure(points,1920,1080,'right','basketball');
assert.equal(m.elbow,90);assert.equal(m.knee,180);assert.equal(m.lean,0);
assert.equal(measure(points,1920,1080,'right','golf').elbow,null);
assert.equal(measure(points,1920,1080,'left','golf').elbow,90);
assert.equal(measure(null,1920,1080).lean,null);
const s=summary([{...m,landmarks:points},{...m,hipX:m.hipX+216,landmarks:points}]);
assert.equal(s.detected,2);assert.ok(Math.abs(s.horizontalSpan-.5)<1e-9);
assert.equal(summary([]).horizontalSpan,null);
assert.equal(timing('golf',{address:0,top:3,impact:4,finish:5}).ratio,3);
assert.ok(timing('golf',{address:0,top:3,impact:2,finish:5}).error);
assert.equal(timing('basketball',{}).complete,false);
const fs=await import('node:fs/promises');
const landing=await fs.readFile('./dist/index.html','utf8');
const appHtml=await fs.readFile('./dist/app/index.html','utf8');
assert.match(landing,/href="\/app\//);
for(const asset of ['landing.js','data:image/jpeg;base64,','--ml-banner3','--ml-banner4','--ml-banner5','--ml-banner6','hero-banner-c','aria-label="Illustrative basketball form artwork'])assert.ok(landing.includes(asset),`Landing page must include ${asset}`);
const landingCss=await fs.readFile('./dist/landing.css','utf8');assert.match(landingCss,/@keyframes banner-c/);
const landingIcon=landing.match(/<link rel="icon" href="([^"]+)"/),appIcon=appHtml.match(/<link rel="icon" href="([^"]+)"/);assert.ok(landingIcon&&appIcon);assert.equal(landingIcon[1],appIcon[1],'Home and app tab icons must match');
assert.match(appHtml,/href="\/style\.css/);assert.match(appHtml,/src="\/app\.js/);
const server=await fs.readFile('./server.mjs','utf8');const model=await fs.readFile('./access/model.mjs','utf8');
for(const asset of ['landing.js','moster-banner3.png','moster-banner4.png'])assert.ok(server.includes(`'${asset}'`),`Server must serve ${asset}`);
assert.ok(model.includes('basketball-shooting-release-transition-v1.md'),'Basketball endpoint must load the new conditional knowledge module');
// knowledge/ is private and git-ignored; validate its content only where it exists.
const priorityKB=await fs.readFile('./knowledge/basketball-shooting-release-transition-v1.md','utf8').catch(()=>null);if(priorityKB)assert.match(priorityKB,/source_case: IMG_4216/);if(priorityKB){assert.match(priorityKB,/original video was not re-reviewed/);assert.ok(priorityKB.includes('不代表所有投籃者都必然有相同缺點'));}
const html=appHtml;
const js=await fs.readFile('./dist/app.js','utf8');
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]));
assert.match(appHtml,/href="\/style\.css/);assert.match(appHtml,/src="\/app\.js/);
assert.doesNotThrow(()=>new Function(js.replace(/^import .*;\s*$/gm,'')),'App script must parse before upload events can be attached');
for(const [,id] of js.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(id),`Missing element ${id}`);
for(const path of ['style.css','app.js','metrics.mjs'])await fs.access(`dist/${path}`);
console.log('PASS: geometry, visibility, shooting/lead side selection, missing poses, displacement, timing order, and UI element bindings.');
const {selectCandidate,fitRect,delta,inferBodyPart,bodyPartPositions}=await import('./dist/graphic.mjs');
assert.equal(selectCandidate(null,{knee:null},'knee','min'),false);
assert.equal(selectCandidate({sample:{knee:100}},{knee:90},'knee','min'),true);
assert.equal(selectCandidate({sample:{elbow:170}},{elbow:90},'elbow','max'),false);
assert.equal(delta(null,20),null);assert.equal(delta(90,120),30);
assert.deepEqual(fitRect(100,200,0,0,100,100),{x:25,y:0,w:50,h:100});
assert.equal(inferBodyPart({title:'投籃肘部的位置'}),'elbow');
assert.equal(inferBodyPart({title:'節奏待確認'}),null);
assert.deepEqual(bodyPartPositions({landmarks:points},'elbow','right','basketball'),[points[14]]);
assert.deepEqual(bodyPartPositions({landmarks:points},'hand','right','basketball'),[points[16]]);
assert.deepEqual(bodyPartPositions({landmarks:points},'foot','right','basketball'),[points[28]]);
const graphicJS=await fs.readFile('./dist/graphic.mjs','utf8');
for(const [,id] of graphicJS.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(id),`Missing graphic element ${id}`);
console.log('PASS: graphic frame selection, missing metrics, angle differences, portrait aspect ratio and controls.');

const coachJS=await fs.readFile('./dist/coach.mjs','utf8');
for(const [,id] of coachJS.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(id),`Missing coach element ${id}`);
console.log('PASS: AI comparison UI bindings.');
